version: 2
project_name: trigger-dev-pp-cli
changelog:
  disable: true
builds:
  - id: trigger-dev-pp-cli
    main: ./cmd/trigger-dev-pp-cli
    binary: trigger-dev-pp-cli
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/mvanhorn/printing-press-library/library/developer-tools/trigger-dev/internal/cli.version={{ .Version }}
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - windows_arm64
  - id: trigger-dev-pp-mcp
    main: ./cmd/trigger-dev-pp-mcp
    binary: trigger-dev-pp-mcp
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - windows_arm64
archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]
checksum:
  name_template: checksums.txt
brews:
  - name: trigger-dev-pp-cli
    repository:
      owner: trevin-chow
      name: homebrew-tap
    homepage: "https://github.com/mvanhorn/printing-press-library"
    description: "The REST API lets you trigger and manage runs on Trigger.dev. You can trigger a run, get the status of a run, and get the results of a run."
    install: |
      bin.install "trigger-dev-pp-cli"
      bin.install "trigger-dev-pp-mcp"
